'use client';

import { useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { Activity, BookOpenCheck, ClipboardCheck, Database, FileClock, ListChecks, LogOut, Search, ShieldCheck, Users, WalletCards } from 'lucide-react';
import type { AuditEvent, Booking, Listing, ModerationItem, PaymentStatus, PublicUser } from '@/lib/domain';
import { handleResponse, isAuthenticationError } from '@/services/api.service';
import { DashboardLoadState } from '@/components/common/DashboardLoadState';

type AdminData = { user: PublicUser; listings: Listing[]; bookings: Booking[]; directory: PublicUser[]; moderation: ModerationItem[]; audit: AuditEvent[]; metrics: { held:number;released:number;frozen:number;activeUsers:number;pendingProfiles:number }; integrations:{database:boolean;openAI:boolean;gemini:boolean;weather:boolean;amadeus:boolean;payMongo:boolean} };
type Tab='overview'|'moderation'|'users'|'listings'|'payments'|'audit';
async function request(body?:Record<string,unknown>){const response=await fetch(body?'/api/platform':'/api/platform?scope=admin',body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:undefined);return handleResponse<AdminData & {result?:unknown}>(response)}
const money=(value:number)=>`PHP ${value.toLocaleString()}`;
const PAYMENT_OPTIONS: Record<PaymentStatus, PaymentStatus[]> = {PAID_HELD:['PAID_HELD','Released','FROZEN_HELD','REFUNDED'],FROZEN_HELD:['FROZEN_HELD','PAID_HELD','REFUNDED'],Released:['Released'],REFUNDED:['REFUNDED']};
const paymentOptions=(status:PaymentStatus):PaymentStatus[]=>PAYMENT_OPTIONS[status];

export default function AdminDashboard(){
 const router=useRouter();const[data,setData]=useState<AdminData|null>(null);const[tab,setTab]=useState<Tab>('overview');const[message,setMessage]=useState('');const[search,setSearch]=useState('');const[filter,setFilter]=useState('all');const[busy,setBusy]=useState(false);const[loadError,setLoadError]=useState('');
 const refresh=()=>request().then(setData);
 const loadInitial=async()=>{try{setData(await request())}catch(error){if(isAuthenticationError(error)){router.replace('/');return}setLoadError(error instanceof Error?error.message:'TravelMate could not load the admin control room.')}};
 useEffect(()=>{void request().then(setData).catch((error:unknown)=>{if(isAuthenticationError(error)){router.replace('/');return}setLoadError(error instanceof Error?error.message:'TravelMate could not load the admin control room.')})},[router]);
 async function act(body:Record<string,unknown>,success='Action persisted and added to the audit log.'){setBusy(true);setMessage('');try{await request(body);await refresh();setMessage(success)}catch(error){setMessage(error instanceof Error?error.message:'Action failed.')}finally{setBusy(false)}}
 async function logout(){await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'logout'})});router.replace('/')}
 const users=useMemo(()=>data?.directory.filter(item=>(filter==='all'||item.role===filter||item.accountStatus===filter)&&`${item.name} ${item.email}`.toLowerCase().includes(search.toLowerCase()))??[],[data,filter,search]);
 const listings=useMemo(()=>data?.listings.filter(item=>(filter==='all'||item.status===filter)&&item.name.toLowerCase().includes(search.toLowerCase()))??[],[data,filter,search]);
 if(!data)return <DashboardLoadState label="the admin control room" error={loadError} onRetry={()=>{setLoadError('');void loadInitial()}}/>;
 const listingName=(id:string)=>data.listings.find(item=>item.id===id)?.name||id;const userName=(id:string)=>data.directory.find(item=>item.id===id)?.name||id;
 return <div className="min-h-screen bg-[#07111f] text-slate-100">
  <header className="sticky top-0 z-40 h-16 border-b border-slate-800 bg-[#07111f]/95 backdrop-blur px-5 flex items-center justify-between"><button onClick={()=>router.push('/')} className="font-extrabold flex gap-2"><ShieldCheck className="text-cyan-400"/>TravelMate Admin</button><button type="button" aria-label="Sign out" title="Sign out" onClick={logout} className="p-2"><LogOut size={18}/></button></header>
  <div className="max-w-7xl mx-auto grid lg:grid-cols-[210px_1fr] gap-8 px-4 lg:px-8"><aside aria-label="Admin workspace" className="py-5 lg:py-8 flex lg:flex-col gap-1 overflow-x-auto">{([['overview','Overview',Activity],['moderation','Moderation',ClipboardCheck],['users','Users',Users],['listings','Listings',ListChecks],['payments','Payments',WalletCards],['audit','Audit & health',FileClock]] as const).map(([id,label,Icon])=><button key={id} aria-current={tab===id?'page':undefined} onClick={()=>{setTab(id);setFilter('all');setSearch('')}} className={`shrink-0 flex items-center gap-2 px-3 py-2 rounded-md text-sm font-semibold ${tab===id?'bg-cyan-400 text-slate-950':'text-slate-400 hover:bg-slate-900'}`}><Icon size={16}/>{label}{id==='moderation'&&data.moderation.length>0&&<span className="ml-auto bg-amber-400 text-slate-950 rounded-full px-1.5 text-[10px]">{data.moderation.length}</span>}</button>)}</aside>
  <main className="py-5 lg:py-8 min-w-0"><div className="mb-7"><p className="text-xs uppercase tracking-widest text-cyan-400">System control room</p><h1 className="text-2xl font-bold">{tab==='audit'?'Audit and system health':tab[0].toUpperCase()+tab.slice(1)}</h1></div>{message&&<p role="status" className="mb-5 border border-slate-700 bg-slate-900 px-4 py-3 rounded-md text-sm">{message}</p>}

  {tab==='overview'&&<div className="space-y-8"><section className="grid sm:grid-cols-2 xl:grid-cols-4 gap-4"><Stat label="Active users" value={String(data.metrics.activeUsers)}/><Stat label="Pending queue" value={String(data.moderation.length)}/><Stat label="Bookings" value={String(data.bookings.length)}/><Stat label="Payment volume" value={money(data.bookings.reduce((s,x)=>s+x.amount,0))}/></section><section className="grid lg:grid-cols-[1.2fr_.8fr] gap-8"><div><SectionTitle title="Priority queue"/>{data.moderation.length===0?<Empty text="No pending moderation or disputes."/>:<div className="divide-y divide-slate-800">{data.moderation.slice(0,5).map(item=><button key={item.id} onClick={()=>setTab('moderation')} className="w-full py-4 text-left flex justify-between"><div><strong className="text-sm">{item.title}</strong><p className="text-xs text-slate-500">{item.details}</p></div><Status value={item.kind}/></button>)}</div>}</div><div><SectionTitle title="Payment exposure"/><div className="grid gap-3"><Stat label="Held" value={money(data.metrics.held)}/><Stat label="Frozen" value={money(data.metrics.frozen)}/><Stat label="Released" value={money(data.metrics.released)}/></div></div></section></div>}

  {tab==='moderation'&&<div className="space-y-3">{data.moderation.length===0?<Empty text="Queue is clear."/>:data.moderation.map(item=><article key={item.id} className="border border-slate-800 rounded-md p-4 flex flex-col md:flex-row md:items-center justify-between gap-4"><div><Status value={item.kind}/><h3 className="font-bold mt-1">{item.title}</h3><p className="text-sm text-slate-400">{item.details}</p><p className="text-xs text-slate-600 mt-1">{new Date(item.createdAt).toLocaleString()}</p></div><div className="flex gap-2 shrink-0">{item.kind==='dispute'?<><button disabled={busy} onClick={()=>act({action:'resolve-dispute',id:item.id,decision:'traveler'},'Traveler refunded; dispute resolved.')} className="bg-emerald-400 text-slate-950 px-3 py-2 rounded-md text-xs font-bold">Refund traveler</button><button disabled={busy} onClick={()=>act({action:'resolve-dispute',id:item.id,decision:'owner'},'Held payment restored; dispute resolved.')} className="border border-amber-600 px-3 py-2 rounded-md text-xs">Rule owner</button></>:<><button disabled={busy} onClick={()=>act({action:'moderate',id:item.id,decision:'approve'})} className="bg-emerald-400 text-slate-950 px-3 py-2 rounded-md text-xs font-bold">Approve</button><button disabled={busy} onClick={()=>act({action:'moderate',id:item.id,decision:'reject'})} className="border border-red-700 text-red-300 px-3 py-2 rounded-md text-xs">Reject</button></>}</div></article>)}</div>}

  {tab==='users'&&<div className="space-y-4"><Toolbar search={search} onSearch={setSearch} filter={filter} onFilter={setFilter} options={[['all','All users'],['traveler','Travelers'],['owner','Owners'],['active','Active'],['suspended','Suspended']]}/><div className="overflow-x-auto border border-slate-800 rounded-md"><table className="w-full min-w-[860px] text-sm"><thead className="bg-slate-900 text-xs text-slate-400"><tr><th className="text-left p-3">User</th><th className="text-left">Role</th><th className="text-left">Verification</th><th className="text-left">Trust</th><th className="text-left">Status</th><th className="text-right p-3">Controls</th></tr></thead><tbody>{users.map(item=><tr key={item.id} className="border-t border-slate-800"><td className="p-3"><strong>{item.name}</strong><p className="text-xs text-slate-500">{item.email}</p></td><td>{item.role}</td><td><Status value={item.profileStatus}/></td><td><div className="flex items-center gap-2"><input aria-label={`${item.name} trust score`} type="number" min="0" max="100" defaultValue={item.trustScore} className="w-16 bg-slate-950 border border-slate-700 rounded px-2 py-1" onKeyDown={e=>{if(e.key==='Enter')void act({action:'admin-trust-score',id:item.id,score:Number(e.currentTarget.value)},'Trust score updated.')}}/><span className="text-xs text-slate-500">/100</span></div></td><td><Status value={item.accountStatus}/></td><td className="p-3 text-right">{item.role!=='admin'&&<button disabled={busy} onClick={()=>act({action:'admin-user-status',id:item.id,status:item.accountStatus==='active'?'suspended':'active'},item.accountStatus==='active'?'Account suspended.':'Account restored.')} className={`border px-3 py-1 rounded-md text-xs ${item.accountStatus==='active'?'border-red-700 text-red-300':'border-emerald-600 text-emerald-300'}`}>{item.accountStatus==='active'?'Suspend':'Restore'}</button>}</td></tr>)}</tbody></table></div></div>}

  {tab==='listings'&&<div className="space-y-4"><Toolbar search={search} onSearch={setSearch} filter={filter} onFilter={setFilter} options={[['all','All listings'],['approved','Approved'],['pending','Pending'],['rejected','Rejected']]}/><div className="overflow-x-auto border border-slate-800 rounded-md"><table className="w-full min-w-[850px] text-sm"><thead className="bg-slate-900 text-xs text-slate-400"><tr><th className="text-left p-3">Listing</th><th className="text-left">Owner</th><th className="text-left">Price</th><th className="text-left">Capacity</th><th className="text-left">Status</th><th className="text-right p-3">Control</th></tr></thead><tbody>{listings.map(item=><tr key={item.id} className="border-t border-slate-800"><td className="p-3"><strong>{item.name}</strong><p className="text-xs text-slate-500">{item.category} · {item.address||'No address'}</p></td><td>{userName(item.ownerId)}</td><td>{money(item.price)}</td><td>{item.available}/{item.capacity}</td><td><Status value={item.status}/></td><td className="p-3 text-right"><select aria-label={`${item.name} status`} value={item.status} onChange={e=>void act({action:'admin-listing-status',id:item.id,status:e.target.value},'Listing status updated.')} className="bg-slate-950 border border-slate-700 rounded px-2 py-1 text-xs"><option value="pending">Pending</option><option value="approved">Approved</option><option value="rejected">Rejected</option></select></td></tr>)}</tbody></table></div></div>}

  {tab==='payments'&&<div className="space-y-6"><p className="rounded-md border border-amber-900 bg-amber-950/20 p-3 text-sm text-amber-200">This is a simulated payment ledger; PayMongo is not connected and no money is transferred.</p><section className="grid sm:grid-cols-3 gap-4"><Stat label="Held (simulated)" value={money(data.metrics.held)}/><Stat label="Frozen (simulated)" value={money(data.metrics.frozen)}/><Stat label="Released (simulated)" value={money(data.metrics.released)}/></section><div className="overflow-x-auto border border-slate-800 rounded-md"><table className="w-full min-w-[900px] text-sm"><thead className="bg-slate-900 text-xs text-slate-400"><tr><th className="text-left p-3">Booking</th><th className="text-left">Traveler</th><th className="text-left">Listing</th><th className="text-left">Amount</th><th className="text-left">Booking state</th><th className="text-right p-3">Payment state</th></tr></thead><tbody>{data.bookings.map(item=><tr key={item.id} className="border-t border-slate-800"><td className="p-3 font-mono text-xs">{item.id.slice(0,14)}…</td><td>{userName(item.travelerId)}</td><td>{listingName(item.listingId)}</td><td>{money(item.amount)}</td><td><Status value={item.status}/></td><td className="p-3 text-right"><select disabled={busy||paymentOptions(item.paymentStatus).length===1} aria-label={`${item.id} payment status`} value={item.paymentStatus} onChange={e=>void act({action:'admin-payment-status',id:item.id,status:e.target.value},'Simulated payment state updated.')} className="bg-slate-950 border border-slate-700 rounded px-2 py-1 text-xs disabled:opacity-50">{paymentOptions(item.paymentStatus).map(status=><option key={status}>{status}</option>)}</select></td></tr>)}</tbody></table></div></div>}

  {tab==='audit'&&<div className="grid lg:grid-cols-[1fr_320px] gap-8"><section><SectionTitle title="Audit trail"/><div className="mb-3 relative"><Search size={15} className="absolute left-3 top-3 text-slate-500"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Filter actions or target IDs" className="w-full bg-slate-950 border border-slate-700 rounded-md pl-9 pr-3 py-2 text-sm"/></div><div className="font-mono text-xs divide-y divide-slate-800">{data.audit.filter(item=>`${item.action} ${item.targetId}`.toLowerCase().includes(search.toLowerCase())).map(item=><div key={item.id} className="py-3 grid sm:grid-cols-[170px_150px_1fr] gap-2"><span className="text-slate-500">{new Date(item.createdAt).toLocaleString()}</span><span className="text-cyan-300">{item.action}</span><span className="truncate">{item.targetId}</span></div>)}</div></section><aside><SectionTitle title="System health"/><div className="border border-slate-800 rounded-md divide-y divide-slate-800">{Object.entries(data.integrations).map(([name,ready])=><div key={name} className="p-3 flex justify-between text-sm"><span className="flex items-center gap-2">{name==='database'?<Database size={15}/>:name==='payMongo'?<WalletCards size={15}/>:<BookOpenCheck size={15}/>} {name}</span><span className={ready?'text-emerald-300':'text-amber-300'}>{ready?'Connected':'Not configured'}</span></div>)}</div></aside></div>}
  </main></div></div>;
}

function Toolbar({search,onSearch,filter,onFilter,options}:{search:string;onSearch:(v:string)=>void;filter:string;onFilter:(v:string)=>void;options:string[][]}){return <div className="flex gap-2 max-w-xl"><label className="relative flex-1"><span className="sr-only">Search records</span><Search size={15} className="absolute left-3 top-3 text-slate-500"/><input value={search} onChange={e=>onSearch(e.target.value)} placeholder="Search" className="w-full bg-slate-950 border border-slate-700 rounded-md pl-9 pr-3 py-2 text-sm"/></label><select aria-label="Filter records" value={filter} onChange={e=>onFilter(e.target.value)} className="bg-slate-950 border border-slate-700 rounded-md px-3 text-sm">{options.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></div>}
function Stat({label,value}:{label:string;value:string}){return <div className="border-t border-slate-700 py-4 min-w-0"><p className="text-xs uppercase text-slate-500">{label}</p><strong className="text-xl break-words">{value}</strong></div>}
function SectionTitle({title}:{title:string}){return <h2 className="font-bold text-lg mb-3">{title}</h2>}
function Status({value}:{value:string}){const positive=['approved','verified','active','confirmed','completed'].includes(value);const danger=['rejected','suspended','cancelled'].includes(value);return <span className={`text-xs ${positive?'text-emerald-300':danger?'text-red-300':'text-amber-300'}`}>{value.replaceAll('_',' ')}</span>}
function Empty({text}:{text:string}){return <p className="text-sm text-slate-500 py-6">{text}</p>}
