import Image from 'next/image';
import { BedDouble, BusFront, ChevronDown, ChevronUp, Clock3, CloudSun, Eye, MapPin, Pencil, Plus, Save, Trash2 } from 'lucide-react';
import { ReferenceAmount } from '@/components/common/ReferenceAmount';
import type { ExchangeRateQuote, ItineraryResponse, WeatherData } from '@/lib/contracts';
import { formatMoney, partyBudgetLabel, partyEstimateLabel, partySpendLabel, PARTY_TYPE_LABELS, type CurrencyCode } from '@/lib/domain';
import { verifiedPlaceImage } from '@/lib/place-image';

type Props = {
  itinerary: ItineraryResponse;
  weather: WeatherData | null;
  manualDirty: boolean;
  editingTripId: string | null;
  busy: boolean;
  travelers: number;
  referenceCurrency: CurrencyCode;
  exchangeQuotes: Partial<Record<CurrencyCode, ExchangeRateQuote>>;
  onSave: () => void;
  onBookAccommodation: (listingId: string, nights: number) => void;
  onReorderActivity: (dayIndex: number, activityIndex: number, direction: -1 | 1) => void;
  onEditActivity: (dayIndex: number, activityIndex: number | null) => void;
  onRemoveActivity: (dayIndex: number, activityIndex: number) => void;
  onOpenDay: (day: ItineraryResponse['days'][number]) => void;
};

export function ItineraryWorkspace({ itinerary, weather, manualDirty, editingTripId, busy, travelers, referenceCurrency, exchangeQuotes, onSave, onBookAccommodation, onReorderActivity, onEditActivity, onRemoveActivity, onOpenDay }: Props) {
  return <>
    <div className="my-5 flex flex-wrap items-center justify-between gap-3">
      <div><h2 className="text-xl font-bold">{itinerary.destination}</h2><p className="text-xs uppercase tracking-widest text-cyan-300">{itinerary.source === 'gemini' ? 'Gemini generated' : itinerary.source === 'openai' ? 'OpenAI generated' : 'Demo fallback'}{itinerary.manuallyEdited || manualDirty ? ' · manually edited' : ''}</p><p className="mt-1 text-xs text-white/45">{editingTripId ? 'This plan is saved. Save again after manual changes.' : manualDirty ? 'Automatic save failed; a browser draft is protecting this plan.' : 'Saving this generated plan...'}</p></div>
      <button disabled={busy} onClick={onSave} className={`flex min-h-10 items-center gap-2 rounded-lg px-4 py-2 text-sm font-bold transition disabled:opacity-50 ${manualDirty ? 'bg-amber-400 text-slate-950 hover:bg-amber-300' : 'border border-slate-600 hover:bg-slate-800'}`}><Save size={15}/>{busy ? 'Saving...' : manualDirty ? 'Save manual changes' : editingTripId ? 'Update saved trip' : 'Save trip'}</button>
    </div>
    {itinerary.costSharing && <section className={`mb-5 grid gap-3 border-y border-slate-800 py-4 ${travelers > 1 ? 'sm:grid-cols-3' : 'sm:grid-cols-2'}`}><div><p className="text-xs uppercase text-slate-500">Party</p><strong>{PARTY_TYPE_LABELS[itinerary.costSharing.partyType]} · {itinerary.costSharing.travelers} traveler{itinerary.costSharing.travelers === 1 ? '' : 's'}</strong><p className="mt-1 text-xs text-slate-500">{partyBudgetLabel(itinerary.costSharing.partyType, itinerary.costSharing.travelers)}</p></div><div><p className="text-xs uppercase text-slate-500">{partySpendLabel(itinerary.costSharing.partyType)}</p><strong>{formatMoney(itinerary.costSharing.plannedGroupSpend, itinerary.currency)}</strong><ReferenceAmount amount={itinerary.costSharing.plannedGroupSpend} currency={itinerary.currency} referenceCurrency={referenceCurrency} quotes={exchangeQuotes}/></div>{travelers > 1 && <div><p className="text-xs uppercase text-slate-500">Equal share guide</p><strong>{formatMoney(itinerary.costSharing.plannedSpendShares[0], itinerary.currency)} per traveler</strong><ReferenceAmount amount={itinerary.costSharing.plannedSpendShares[0]} currency={itinerary.currency} referenceCurrency={referenceCurrency} quotes={exchangeQuotes}/>{new Set(itinerary.costSharing.plannedSpendShares).size > 1 && <p className="text-xs text-slate-500">A one-unit remainder is assigned to the first traveler.</p>}</div>}</section>}
    {itinerary.accommodation && <section className="mb-5 grid items-center gap-4 border-b border-slate-800 pb-4 sm:grid-cols-[1fr_auto]"><div className="flex items-start gap-3"><BedDouble className="shrink-0 text-amber-300"/><div><strong>{itinerary.accommodation.name}</strong><p className="text-sm text-slate-400">{itinerary.accommodation.address || itinerary.destination}</p><p className="text-sm">{formatMoney(itinerary.accommodation.nightlyRate, itinerary.currency)}/night x {itinerary.accommodation.nights} nights = <strong>{formatMoney(itinerary.accommodation.total, itinerary.currency)} group total</strong></p><ReferenceAmount amount={itinerary.accommodation.total} currency={itinerary.currency} referenceCurrency={referenceCurrency} quotes={exchangeQuotes}/>{itinerary.costSharing && <p className="text-xs text-slate-400">Equal accommodation share: {formatMoney(itinerary.costSharing.accommodationShares[0], itinerary.currency)}{travelers > 1 ? ' per traveler' : ''}<ReferenceAmount amount={itinerary.costSharing.accommodationShares[0]} currency={itinerary.currency} referenceCurrency={referenceCurrency} quotes={exchangeQuotes}/></p>}</div></div>{itinerary.accommodation.source === 'amadeus' ? <span className="rounded-md border border-cyan-700 px-4 py-2 text-sm text-cyan-200">{itinerary.accommodation.isLive ? 'Live' : 'Test'} Amadeus offer selected</span> : <button disabled={busy} onClick={() => onBookAccommodation(itinerary.accommodation!.listingId, itinerary.accommodation!.nights)} className="rounded-md bg-emerald-400 px-4 py-2 text-sm font-bold text-slate-950">Book as lead traveler</button>}</section>}
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
      {itinerary.days.map((day, dayIndex) => <article key={day.day} className="overflow-hidden rounded-xl border border-slate-800 bg-slate-900/50">
        <div className="relative aspect-[16/9] bg-slate-900">
          {verifiedPlaceImage(day.imageUrl) ? <Image src={verifiedPlaceImage(day.imageUrl)!} alt={`${day.theme} in ${itinerary.destination}`} fill sizes="(max-width: 768px) 100vw, (max-width: 1280px) 50vw, 33vw" className="object-cover"/> : <div className="grid h-full place-items-center px-6 text-center text-xs text-slate-500"><span><MapPin className="mx-auto mb-2" size={22}/>No verified place photo available for this day.</span></div>}
          <span className="absolute left-3 top-3 bg-slate-950/85 px-2 py-1 text-xs font-bold text-amber-300">DAY {day.day}</span>
          <span className="absolute right-3 top-3 bg-slate-950/85 px-2 py-1 text-right font-mono text-sm">{formatMoney(day.totalCost, itinerary.currency)}<ReferenceAmount amount={day.totalCost} currency={itinerary.currency} referenceCurrency={referenceCurrency} quotes={exchangeQuotes}/></span>
          {day.imageAttribution && <a href={day.imageAttribution.sourceUrl} target="_blank" rel="noreferrer" title={`${day.imageAttribution.creator} · ${day.imageAttribution.license}`} className="absolute bottom-2 right-2 max-w-[75%] truncate rounded bg-slate-950/80 px-2 py-1 text-[9px] text-slate-300">Photo: {day.imageAttribution.creator} · {day.imageAttribution.license}</a>}
        </div>
        <div className="p-4">
          <h3 className="font-bold">{day.theme}</h3><p className="text-xs text-slate-500">{day.date}</p>
          {day.travelNote && <p className="mt-2 flex items-start gap-2 text-xs leading-relaxed text-cyan-200"><Clock3 size={14} className="mt-0.5 shrink-0"/>{day.travelNote}</p>}
          {day.crowdLevel && <div className="mt-2 border-l border-violet-400/50 pl-3 text-xs leading-5 text-violet-200"><p title={day.crowdNote}>Estimated crowd: <strong className="capitalize">{day.crowdLevel}</strong> · low confidence · not live data</p>{day.crowdRecommendation && <p className="mt-1 text-white/52">{day.crowdRecommendation}</p>}{day.crowdFetchedAt && <p className="mt-1 text-[10px] text-white/32">Estimated {new Date(day.crowdFetchedAt).toLocaleString()}</p>}</div>}
          {weather?.forecast.find((forecast) => forecast.date === day.date) && <p className="mt-2 text-xs text-sky-200"><CloudSun size={14} className="mr-1 inline"/>{weather.forecast.find((forecast) => forecast.date === day.date)!.description}, {weather.forecast.find((forecast) => forecast.date === day.date)!.tempMin}°–{weather.forecast.find((forecast) => forecast.date === day.date)!.tempMax}°C · {weather.forecast.find((forecast) => forecast.date === day.date)!.precipitationProbability}% rain</p>}
          {weather?.forecast.find((forecast) => forecast.date === day.date)?.weatherAlert && <p className="mt-1 text-xs text-amber-300">{weather.forecast.find((forecast) => forecast.date === day.date)!.weatherAlert}</p>}
          <p className="mt-2 flex flex-wrap items-center gap-x-2 text-xs text-emerald-200"><BusFront size={14}/>Estimated ride/boat fare: {formatMoney(day.rideFare || 0, itinerary.currency)}<ReferenceAmount amount={day.rideFare || 0} currency={itinerary.currency} referenceCurrency={referenceCurrency} quotes={exchangeQuotes} className="text-[10px] font-normal text-cyan-200/70"/></p>
          <ul className="mt-3 space-y-2" aria-label={`Day ${day.day} activities`}>{day.activities.length === 0 ? <li className="rounded-lg border border-dashed border-slate-700 px-3 py-5 text-center text-xs text-slate-500">No activities yet. Add one to build this day.</li> : day.activities.map((item, activityIndex) => <li key={`${item.time}-${item.title}-${activityIndex}`} className="rounded-lg border border-slate-800 bg-slate-950/40 p-3 text-sm"><div className="flex items-start justify-between gap-3"><span className="min-w-0"><span className="mr-2 text-xs text-cyan-300">{item.time}</span><strong className="font-semibold">{item.title}</strong><small className="mt-1 block text-slate-500">{formatMoney(item.estimatedCost, itinerary.currency)} {partyEstimateLabel(itinerary.partyType || 'solo')}</small><ReferenceAmount amount={item.estimatedCost} currency={itinerary.currency} referenceCurrency={referenceCurrency} quotes={exchangeQuotes}/></span><span className="flex shrink-0 items-center gap-0.5"><button disabled={activityIndex === 0} onClick={() => onReorderActivity(dayIndex, activityIndex, -1)} aria-label={`Move ${item.title} earlier`} title="Move earlier" className="rounded p-1.5 text-slate-400 hover:bg-slate-800 hover:text-white disabled:opacity-25"><ChevronUp size={14}/></button><button disabled={activityIndex === day.activities.length - 1} onClick={() => onReorderActivity(dayIndex, activityIndex, 1)} aria-label={`Move ${item.title} later`} title="Move later" className="rounded p-1.5 text-slate-400 hover:bg-slate-800 hover:text-white disabled:opacity-25"><ChevronDown size={14}/></button><button onClick={() => onEditActivity(dayIndex, activityIndex)} aria-label={`Edit ${item.title}`} title="Edit activity" className="rounded p-1.5 text-slate-400 hover:bg-slate-800 hover:text-cyan-300"><Pencil size={14}/></button><button onClick={() => onRemoveActivity(dayIndex, activityIndex)} aria-label={`Remove ${item.title}`} title="Remove activity" className="rounded p-1.5 text-slate-400 hover:bg-red-950 hover:text-red-300"><Trash2 size={14}/></button></span></div></li>)}</ul>
          {day.returnToStayAt && itinerary.accommodation && <p className="mt-3 flex items-center gap-2 border-t border-slate-800 pt-3 text-xs text-amber-200"><BedDouble size={14}/>Return to {itinerary.accommodation.name} by {day.returnToStayAt}</p>}
          <div className="mt-4 grid grid-cols-2 gap-2"><button disabled={day.activities.length >= 8} onClick={() => onEditActivity(dayIndex, null)} className="flex items-center justify-center gap-2 rounded-md border border-amber-500/40 px-3 py-2 text-sm font-semibold text-amber-300 hover:bg-amber-400/10 disabled:opacity-40"><Plus size={15}/>Add activity</button><button onClick={() => onOpenDay(day)} className="flex items-center justify-center gap-2 rounded-md border border-slate-700 px-3 py-2 text-sm font-semibold hover:bg-slate-800"><Eye size={15}/>Full details</button></div>
        </div>
      </article>)}
    </div>
  </>;
}
